apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-gemma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llm-gemma
  template:
    metadata:
      labels:
        app: llm-gemma
    spec:
      containers:
      - name: llm-gemma
        image: mybvc365/drone_ai:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 11434
        command: ["python3", "Chat2.py"]
        # If you want this to interact with Ollama on localhost,
        # make sure Ollama is running in the same pod or as a service

---
apiVersion: v1
kind: Service
metadata:
  name: llm-gemma-service
spec:
  selector:
    app: llm-gemma
  ports:
    - protocol: TCP
      port: 80
      targetPort: 11434
  type: ClusterIP
